spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhongzunfa/spring-cloud-config.git
#          uri: https://github.com/rmzf9192/spring-cloud-config.git
          #username:
          #password:
          search-paths: SC-BOOK-CONFIG
#          skip-ssl-validation: true
  application:
    name: ch11-6-config-server
server:
    port: 9090