spring:
  cloud:
    config:
      server:
        git:
#          uri: https://gitee.com/zhongzunfa/{application}
          uri: https://github.com/rmzf9192/{application}
#          username:
#          password:
          search-paths: SC-BOOK-CONFIG
          skip-ssl-validation: true
  application:
    name: ch11-1-config-server-placeholder
server:
    port: 9090
logging:
  level:
    root: debug
